refactor + new ibc validatebasic test
bandprotocol/chain pull request #108
Opened 2021-06-14 16:29 UTC by songwongtp

Fixed: #XXXX

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-06-14 17:23 UTC, taobun requested changes

2021-06-14 17:23 UTC, taobun commented on x/oracle/types/packets.go
> +	if len(p.RequestKey) > MaxRequestIDLength {
MaxRequestIDLength

2021-06-15 03:41 UTC, taobun requested changes

2021-06-15 03:41 UTC, taobun commented on x/oracle/types/constants.go
> +	WasmExecuteGas  = 5000000
Remove unused variable?

2021-06-15 04:12 UTC, taobun approved these changes

2021-06-15 11:34 UTC, Benzbeeb approved these changes

2021-06-15 11:50 UTC, merged