Patch bank to replace old supply
bandprotocol/chain pull request #12
Opened 2021-02-04 15:40 UTC by thebevrishot

## Implementation details
- Rename from x/supply to x/bank
- Patch logic and comment

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-02-05 07:32 UTC, taobun requested changes

2021-02-05 07:32 UTC, taobun commented on app/app.go
> +	wrappedBankerKeeter := bandbank.NewWrappedBankKeeperBurnToCommunityPool(app.BankKeeper)
Keeper

2021-02-05 07:32 UTC, taobun commented on app/app.go
> +	wrappedBankerKeeter.SetAccountKeeper(app.AccountKeeper)
No need this function on bankKeeper.

2021-02-05 07:32 UTC, taobun commented on app/app.go
>  	app.BankKeeper = bankkeeper.NewBaseKeeper(
Can use wrap bank keeper as app.BankKeeper

2021-02-11 04:12 UTC, taobun requested changes

2021-02-11 04:12 UTC, taobun commented on x/bank/keeper.go
> +}
Remove this

2021-02-11 04:14 UTC, taobun commented
I have an opinion to create a new file `expected_keepers.go` to declare AccountKeeper and DistributeKeeper interface that we want to use. Like other modules should be a good way to do.

2021-03-03 09:17 UTC, thebevrishot commented
@taobun Applied the idea, please review.

2021-03-05 05:15 UTC, taobun requested changes

2021-03-05 05:15 UTC, taobun commented on x/bank/keeper/keeper.go
> +func (k *WrappedBankKeeper) SetDistrKeeper(dk *distrkeeper.Keeper) {
receive types.DistributionKeeper

2021-03-05 05:15 UTC, taobun commented on x/bank/keeper/keeper.go
> +func NewWrappedBankKeeperBurnToCommunityPool(bk bankkeeper.Keeper, acc types.AccountKeeper) *WrappedBankKeeper {
I think BankKeeper can return entire struct (base on their bankkeeper)

2021-03-17 10:19 UTC, taobun requested changes

2021-03-17 10:19 UTC, taobun commented on app/app.go
> +	// wrappedBankerKeeter overrides burn token behavior to instead transfer to community pool.
wrappedBankerKeeper

2021-03-19 03:37 UTC, taobun approved these changes

2021-03-19 03:37 UTC, merged