Fix ApplyQuery to Remember Return Type
bandprotocol/chain pull request #137
Opened 2021-06-30 08:03 UTC by ntchjb

Fixed: -

## Implementation details

Since BaseApp.Query() remember return types of gRPC's methods, before returning result back to the client, using ApplyQuery() without calling `BaseApp.Query()` prevent gRPC server to get return type of the data.

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-06-30 08:07 UTC, taobun requested changes

2021-06-30 08:07 UTC, taobun commented on app/app.go
> +		// See, baseapp/grpcrouter.go and baseapp/grpcserver.go for more information.
... .go on cosmos-sdk for more ...

2021-06-30 08:19 UTC, songwongtp approved these changes

2021-07-01 06:56 UTC, taobun requested changes

2021-07-01 06:56 UTC, taobun commented on app/app.go
```suggestion
      baseRes := app.BaseApp.Query(req)
	hookRes, match := app.hooks.ApplyQuery(req)
	if match {
		return hookRes
	}
	return baseRes
```

2021-07-01 07:33 UTC, taobun approved these changes

2021-07-01 07:34 UTC, songwongtp approved these changes

2021-07-01 10:48 UTC, merged