initial push
bandprotocol/chain pull request #153
Opened 2021-08-17 12:12 UTC by songwongtp

Fixed: #XXXX

bump up to cosmos 0.43
- https://github.com/cosmos/cosmos-sdk/blob/v0.43.0/CHANGELOG.md
- https://github.com/cosmos/ibc-go/blob/v1.0.0/docs/migrations/ibc-migration-043.md

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-08-18 10:38 UTC, p-rial approved these changes

2021-08-18 12:46 UTC, taobun requested changes
Also please check oracle/keys.go to remove escrow address

2021-08-18 12:46 UTC, taobun commented on x/oracle/keeper/relay.go
> +	escrowAddress sdk.AccAddress,
relayer

2021-08-18 12:46 UTC, taobun commented on x/oracle/module.go
>  // Route returns the module's path for message route (SDK AppModule interface).
// Deprecated: Route returns the message routing key for the bank module.

2021-08-19 03:18 UTC, taobun requested changes

2021-08-19 03:18 UTC, taobun commented on cmd/bandd/cmd/root.go
> +	cfg.Seal()
Please check where we should seal the config? here or in `SetBech32AddressPrefixesAndBip44CoinType`

2021-08-19 03:18 UTC, taobun commented on x/oracle/types/packets.go
> -	if len(p.RequestKey) > MaxRequestKeyLength {
Remove `MaxRequestKeyLength` constant

2021-08-19 03:18 UTC, taobun commented on x/oracle/ibc_test.go
> +	// Use Carol as a relayer
Let's send more fund to this relayer to make sure he can pay on some data sources but not enough to pay all data sources and check the balance of treasury and carol still the same.

2021-08-19 03:18 UTC, taobun commented on x/oracle/ibc_test.go
>  }
Add TestIBCPrepareExceedFeeLimit too

2021-08-19 05:11 UTC, taobun reviewed
Can you fix `MaximumOwasmGas`?

2021-08-19 07:09 UTC, taobun approved these changes
LGTM

2021-08-19 07:21 UTC, Benzbeeb approved these changes

2021-08-19 07:23 UTC, Benzbeeb approved these changes

2021-08-19 07:31 UTC, taobun approved these changes

2021-08-19 07:36 UTC, merged