patch to Cosmos v0.44.0
bandprotocol/chain pull request #173
Opened 2021-09-02 03:27 UTC by Benzbeeb

Fixed: #XXXX

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-09-03 11:25 UTC, songwongtp approved these changes

2021-09-03 11:25 UTC, p-rial approved these changes

2021-09-03 11:27 UTC, taobun commented on go.sum
>  github.com/cosmos/cosmos-sdk v0.43.0/go.mod h1:ctcrTEAhei9s8O3KSNvL0dxe+fVQGp07QyRb/7H9JYE=
It's come from ibc-go :D

2021-09-03 12:11 UTC, taobun requested changes
LGTM

2021-09-03 12:11 UTC, taobun approved these changes

2021-09-06 03:14 UTC, Kissadada approved these changes
LGTM

2021-09-06 03:52 UTC, taobun requested changes
Please update changelog and PR description

2021-09-06 04:17 UTC, taobun requested changes

2021-09-06 04:17 UTC, taobun commented on CHANGELOG.md
> +- (bump) Use ibc-go package v1.1.0
Move to v2.3.0

2021-09-06 04:24 UTC, taobun approved these changes
LGTM

2021-09-06 04:24 UTC, merged