Parallel os execution test
bandprotocol/chain pull request #226
Opened 2022-08-09 06:04 UTC by satawatnack

## Implementation details
Parallel oracle scripts execution at end block (waiting for performance test)

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2022-09-09 05:29 UTC, colmazia commented on benchmark/bench_test.go
> +	// },
why not test these cases as well?

2022-09-09 06:42 UTC, RogerKSI requested changes

2022-09-09 06:42 UTC, RogerKSI commented on benchmark/bench_test.go
> +			for _, nr := range []int{0, 1, 2, 3, 4} {
please revert back to 0,1,5,10,20

2022-09-09 06:42 UTC, RogerKSI commented on x/oracle/abci.go
> +const MAX_CONCURRENT_JOBS = 4
please move it to x/oracle/types/constants.go

2022-09-09 06:42 UTC, RogerKSI commented on x/oracle/abci.go
> +const MAX_CONCURRENT_JOBS = 4
think should change the name to be more specific with resolving requests.

2022-09-13 09:20 UTC, colmazia approved these changes

2022-09-14 09:03 UTC, RogerKSI approved these changes

2022-09-14 09:06 UTC, merged