Add MsgDepositRequestPool
bandprotocol/chain pull request #23
Opened 2021-03-09 15:10 UTC by Benzbeeb

Fixed: #XXXX

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-03-12 08:38 UTC, taobun requested changes

2021-03-12 08:38 UTC, taobun commented on proto/oracle/v1/tx.proto
> +  string sender =5;
Call linter by `make proto-all`

2021-03-12 08:38 UTC, taobun commented on x/oracle/types/error.go
> +	ErrInvalidDepositRequestPoolAmount = sdkerrors.Register(ModuleName, 44, "invalid deposit request pool amount")
Where this error has been used?

2021-03-17 10:21 UTC, Benzbeeb commented
We use msg send insteed of deposit request pool

2021-03-17 10:21 UTC, closed without merging