Implemented request pool keeper
bandprotocol/chain pull request #24
Opened 2021-03-11 09:54 UTC by Benzbeeb

Fixed: #XXXX

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-03-19 03:34 UTC, taobun requested changes

2021-03-19 03:34 UTC, taobun commented on x/oracle/types/keys.go
> +	fmt "fmt"
fmt?

2021-03-19 03:34 UTC, taobun commented on x/oracle/types/keys.go
> +// GetEscrowAddress returns the escrow address for the specified channel.
and request key

2021-03-19 03:34 UTC, taobun commented on x/oracle/types/keys.go
> +	// a slash is used to create domain separation between port and channel identifiers to
update comment

2021-03-19 03:34 UTC, taobun commented on x/oracle/testapp/setup.go
> +	Coins1unband        = sdk.NewCoins(sdk.NewInt64Coin("uband", 1))
unband?

2021-03-19 03:34 UTC, taobun commented on x/oracle/keeper/request_pool.go
> +func (k Keeper) DepositRequestPool(ctx sdk.Context, requestKey string, portID string, channelID string, amount sdk.Coins, sender sdk.AccAddress) error {
Move to internal function for test only.

2021-04-01 17:00 UTC, taobun approved these changes

2021-04-02 01:54 UTC, ntchjb commented on x/oracle/types/keys.go
> +	preImage := []byte(Version)
Should we use `func Hash(typ string, key []byte) []byte` instead where `typ` is `Version`?

2021-04-02 02:21 UTC, ntchjb commented on x/oracle/types/keys.go
> +	preImage := []byte(Version)
Oh, the function will be available in the future.

https://github.com/cosmos/cosmos-sdk/pull/8415

May use the current for now.

2021-04-02 02:45 UTC, ntchjb approved these changes

2021-04-02 05:44 UTC, merged