Gas multiplier
bandprotocol/chain pull request #241
Opened 2022-09-09 08:39 UTC by colmazia

Fixed: new gas multiplier for new Owasm gas metering mechanism

## Implementation details
- change max gas per block to 50 millions
- change owasm gas multiplier to 31.5 millions
- change test to match new gas metering
- change gas type from uint32 to uint64
- change base owasm gas from 20000 to 35000

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2022-09-20 09:55 UTC, RogerKSI requested changes

2022-09-20 09:55 UTC, RogerKSI commented on benchmark/helper_test.go
> +	oCode, err := ioutil.ReadFile("./testdata/benchmark-withvrf1000.wasm")
please change the name back.

2022-09-23 04:23 UTC, RogerKSI requested changes

2022-09-23 04:23 UTC, RogerKSI commented on x/oracle/keeper/owasm.go
> +	env := types.NewExecuteEnv(req, k.GetReports(ctx, reqID), ctx.BlockTime(), int64(k.MaxCalldataSize(ctx)))
this one should be k.MaxReportDataSize(ctx).

2022-10-03 07:58 UTC, taobun approved these changes

2022-10-03 07:58 UTC, RogerKSI approved these changes

2022-10-03 07:59 UTC, merged