add feegrant support and fee_payer
bandprotocol/chain pull request #269
Opened 2022-11-08 11:29 UTC by colmazia

Fixed: add feegrant and fee_payer support

## Implementation details

You have to add column "fee_payer"
using this SQL command

ALTER TABLE transactions ADD COLUMN testing3 VARCHAR NOT NULL DEFAULT '';

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2022-11-09 04:43 UTC, taobun requested changes

2022-11-09 04:43 UTC, taobun commented on hooks/emitter/decoder.go
> +	allowance, _ := msg.GetFeeAllowanceI()
if err is not nil, then detail["allowance"] can be {}

2022-11-10 17:37 UTC, RogerKSI approved these changes

2022-11-15 08:40 UTC, taobun approved these changes

2022-11-15 08:40 UTC, merged