Fix rest query
bandprotocol/chain pull request #285
Opened 2023-02-24 07:01 UTC by colmazia

Fixed: Rest query for cosmos 0.46.x

## Implementation details

- used grpc instead of rest
- created new proto file for the grpc
- moved proof out of oracle module

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2023-02-28 05:05 UTC, RogerKSI requested changes

2023-03-07 17:55 UTC, RogerKSI approved these changes

2023-03-14 06:18 UTC, satawatnack approved these changes

2023-03-22 04:17 UTC, taobun requested changes

2023-03-22 04:27 UTC, taobun requested changes

2023-03-22 04:27 UTC, taobun commented on proto/bandchain/v1/oracle/proof.proto
> +  repeated OracleDataProof oracle_data_multi_proof = 2;
Please add `[ (gogoproto.nullable) = false ]` to generate `[]OracleDataProof` not `[]*OracleDataProof`

2023-03-22 04:27 UTC, taobun commented on proto/bandchain/v1/oracle/proof.proto
> +  repeated IAVLMerklePath merkle_paths = 3;
ditto

2023-03-22 04:27 UTC, taobun commented on proto/bandchain/v1/oracle/proof.proto
> +  repeated TMSignature signatures = 4;
ditto

2023-03-30 06:03 UTC, taobun requested changes

2023-03-30 06:03 UTC, taobun commented on client/grpc/oracle/proof/proof.pb.go
> +type CommonEncodedVotePart struct {
We used `hexBytes` to make json encode as hex if you use `[]byte` it will encode with base 64

2023-04-11 17:10 UTC, RogerKSI approved these changes

2023-04-21 04:59 UTC, taobun commented on client/grpc/node/service.go
> +	_ = RegisterServiceHandlerClient(context.Background(), mux, NewServiceClient(clientConn))
Just remove `_ = `

2023-04-21 04:59 UTC, taobun commented on client/grpc/node/service.go
> +	context "context"
No need to rename

2023-04-21 05:01 UTC, RogerKSI commented on client/grpc/node/service.go
> +	_ = RegisterServiceHandlerClient(context.Background(), mux, NewServiceClient(clientConn))
removed

2023-04-21 05:01 UTC, RogerKSI commented on client/grpc/node/service.go
> +	context "context"
removed

2023-04-21 05:02 UTC, taobun approved these changes

2023-04-21 05:04 UTC, RogerKSI approved these changes

2023-04-21 05:05 UTC, merged