Fix request grpc endpoint
bandprotocol/chain pull request #31
Opened 2021-03-16 12:49 UTC by Benzbeeb

Fixed: #XXXX

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-04-23 03:57 UTC, ntchjb approved these changes

2021-05-06 08:46 UTC, ntchjb requested changes

2021-05-06 08:46 UTC, ntchjb commented on proto/oracle/v1/oracle.proto
> +// Result
```suggestion
// OraclePacketResult is oracle request detail with its result
```

2021-05-06 08:46 UTC, ntchjb commented on proto/oracle/v1/oracle.proto
> +      [ (gogoproto.nullable) = false ];
```suggestion
  // RequestPacketData is oracle request information
  OracleRequestPacketData request_packet_data = 1
      [ (gogoproto.nullable) = false ];
  // ResponsePacketData is oracle request's fulfillment results e.g. resolve status, aggregated report value, etc.
  OracleResponsePacketData response_packet_data = 2
      [ (gogoproto.nullable) = false ];
```

2021-05-06 09:36 UTC, ntchjb requested changes

2021-05-06 09:36 UTC, ntchjb commented on proto/oracle/v1/oracle.proto
> +}
```suggestion
```

2021-05-06 09:48 UTC, taobun approved these changes

2021-05-06 09:53 UTC, ntchjb approved these changes

2021-05-06 09:54 UTC, merged