Add simulation test for Oracle module
bandprotocol/chain pull request #318
Opened 2023-08-12 09:50 UTC by RogerKSI

## Implementation details
- Add simulation test for oracle module
- Adjust testing structure to separate testdata and testapp (prevent cycle import)

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2023-09-01 08:54 UTC, colmazia commented
Interesting, would be great to see some demos

2023-09-01 10:06 UTC, colmazia reviewed
Submit a review

2023-09-01 10:10 UTC, RogerKSI commented on Makefile
> -.PHONY: proto-all proto-gen proto-gen-any proto-swagger-gen proto-format proto-lint proto-check-breaking proto-update-deps
added in the bottom.

2023-09-04 04:03 UTC, RogerKSI commented on x/oracle/simulation/operations.go
> +		oCount := keeper.GetOracleScriptCount(ctx)
added

2023-09-04 04:03 UTC, RogerKSI commented on x/oracle/simulation/operations_test.go
> +package simulation_test
added

2023-09-20 08:27 UTC, colmazia approved these changes

2023-09-25 06:07 UTC, satawatnack commented on x/oracle/simulation/operations_test.go
> +				ChainID: "BANDCHAIN",
"BANDCHAIN" const string?

2023-09-25 06:21 UTC, RogerKSI commented on x/oracle/simulation/operations_test.go
> +				ChainID: "BANDCHAIN",
updated

2023-09-26 07:13 UTC, satawatnack approved these changes

2023-11-30 09:17 UTC, RogerKSI commented on x/oracle/simulation/genesis.go
> +// DONTCOVER
removed

2024-02-11 15:03 UTC, RogerKSI commented on x/oracle/abci.go
> +	}
added comment. In the simulation test, it's possible to have empty hash on the first block.

2024-02-21 07:57 UTC, taobun requested changes

2024-02-21 07:57 UTC, taobun commented on x/oracle/abci.go
> +	// On the firsrt block in the test. it's possible to have empty hash.
first

2024-02-22 07:04 UTC, taobun approved these changes

2024-02-22 07:04 UTC, merged