Add flag fee-limit to cmd
bandprotocol/chain pull request #38
Opened 2021-03-23 10:23 UTC by Benzbeeb

Fixed: #XXXX

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-03-23 10:57 UTC, taobun requested changes

2021-03-23 10:57 UTC, taobun commented on x/oracle/client/cli/tx.go
> +
Add treasury flag too

2021-03-28 17:33 UTC, taobun requested changes

2021-03-28 17:33 UTC, taobun commented on x/oracle/client/cli/tx.go
> +			treasury, err = sdk.AccAddressFromBech32(treasuryStr)
treasury, err := sdk.AccAddressFromBech32(treasuryStr) ?

2021-03-28 17:33 UTC, taobun commented on x/oracle/client/cli/tx.go
> +			coinStr, err := cmd.Flags().GetString(flagFeeLimit)
Add `TODO: Support do-not-modify fee`

2021-03-29 05:49 UTC, thebevrishot commented on flusher/flusher/db.py
> +    Column("consensus_address", sa.String, sa.ForeignKey("validators.consensus_address"), primary_key=True,),
Please remove unwanted `,`

2021-03-29 05:49 UTC, thebevrishot commented on flusher/flusher/init.py
> +        {"chain_id": chain_id, "topic": topic, "replay_topic": replay_topic, "kafka_offset": -1, "replay_offset": -1,},
please remove unwanted `,`

2021-03-29 05:49 UTC, thebevrishot commented on flusher/flusher/init.py
> +  WHERE  To_timestamp(requests.request_time) >= Now() - '1 month' :: interval
should be `to_timestamp` or `TO_TIMESTAMP`

2021-03-30 07:27 UTC, thebevrishot approved these changes

2021-03-30 08:20 UTC, taobun requested changes

2021-03-30 08:20 UTC, taobun commented on x/oracle/client/cli/tx.go
> +	cmd.Flags().String(flagFeeLimit, "", "the maximum tokens that will be paid to all data source providers")
It's not a flagFeeLimit. It should be flagFee

2021-03-30 08:20 UTC, taobun commented on x/oracle/client/cli/tx.go
> +	cmd.Flags().String(flagFeeLimit, "", "the maximum tokens that will be paid to all data source providers")
ditto

2021-03-31 04:39 UTC, taobun requested changes

2021-03-31 04:39 UTC, taobun commented on cmd/bandd/cmd/gends.go
> +			feeLimit, err := sdk.ParseCoinsNormalized(args[4])
fee

2021-03-31 09:26 UTC, thebevrishot approved these changes

2021-03-31 11:19 UTC, taobun approved these changes

2021-03-31 11:20 UTC, merged