[Tunnel] implement route - IBC Hook
bandprotocol/chain pull request #485
Opened 2024-11-25 09:42 UTC by satawatnack

## Implementation details
Implement an IBC hook for the tunnel to simplify sending data to the destination contract.

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2025-01-09 08:42 UTC, RogerKSI commented on x/tunnel/types/route_ibc_hook.go
> +	}
TBD: should we allow to use MsgUpdateRoute for ibc-hook route info?

2025-01-09 08:42 UTC, RogerKSI commented on x/tunnel/types/route_ibc_hook.go
> +)
TBD: final denom

2025-01-09 08:42 UTC, RogerKSI commented on x/tunnel/keeper/keeper_packet_ibc_hook.go
> +		uint64(ctx.BlockTime().UnixNano())+interval*uint64(time.Second),
interval * 2 , follow logic on ibc route

2025-02-11 09:47 UTC, RogerKSI commented on x/tunnel/types/route_ibc_hook.go
> +		DestinationContractAddress: destinationContractAddress,
what will happen if the tunnel is created with an empty address? if the same as the wrong address, it's ok.
if not, please validate it.

2025-02-11 09:58 UTC, nkitlabs approved these changes

2025-02-11 09:58 UTC, nkitlabs commented on x/tunnel/types/msgs.go
> +	return m, nil
why not return the result directly?

2025-02-14 10:20 UTC, RogerKSI requested changes

2025-02-14 10:20 UTC, RogerKSI commented on x/tunnel/types/msgs.go
> +}
if you want to use this style (return calling), we do it for other routes here as well.

2025-02-14 10:20 UTC, RogerKSI commented on x/tunnel/types/route_ibc_hook.go
> +	}
I don't think it can be verified since the prefix is not the same as the band. please test it.

2025-02-19 10:19 UTC, RogerKSI approved these changes
LGTM. please test with the contract.

2025-03-04 10:08 UTC, RogerKSI commented on x/tunnel/keeper/keeper_packet_ibc_hook.go
> +	}
Can we make the function receive the amount instead of hardcoding it in the function?

2025-03-04 10:09 UTC, RogerKSI requested changes

2025-03-04 10:09 UTC, RogerKSI commented on x/tunnel/keeper/keeper_packet_ibc_hook.go
> +	err := k.MintIBCHookCoinToAccount(ctx, packet.TunnelID, feePayer)
Can we make the function receive the amount instead of hardcoding it in the function?

2025-03-07 08:57 UTC, colmazia commented on x/tunnel/client/cli/tx.go
> +		Use:   "ibc-hook [channel-id] [destination-contract-address] [initial-deposit] [interval] [signalInfos-json-file]",
Why not signal-infos

2025-04-02 04:43 UTC, taobun approved these changes

2025-04-02 15:23 UTC, RogerKSI approved these changes

2025-04-02 15:23 UTC, merged