[Tunnel] Add Router route
bandprotocol/chain pull request #495
Opened 2024-11-27 11:01 UTC by satawatnack

Fixed: #XXXX

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2025-02-04 10:38 UTC, RogerKSI requested changes

2025-02-04 10:38 UTC, RogerKSI commented on x/tunnel/types/params.go
> +	DefaultRouterIntegrationContract = "router17c2txg2px6vna8a6v4ql4eh4ruvprerhytxvwt2ugp4qr473pajsyj9pgm"
- remove default for channel
- contract will be the same for both testnet and mainnet? if not, please remove it.

2025-02-04 10:38 UTC, RogerKSI commented on proto/band/tunnel/v1beta1/route.proto
> +
start running number from 1

2025-02-04 10:38 UTC, RogerKSI commented on x/tunnel/client/cli/tx.go
> +		Short: "Update router route of a router tunnel",
should we use Router (big R) instead when we mention the name?

2025-02-04 10:38 UTC, RogerKSI commented on x/tunnel/keeper/msg_server.go
> +		}
don't think need to check it for Router.  it should always be available.
Also, if it's not, it can't be reliable and it can be changed later from params.

wdyt?.

2025-02-11 10:30 UTC, nkitlabs submitted a review, later dismissed

2025-02-14 09:48 UTC, satawatnack commented on proto/band/tunnel/v1beta1/route.proto
> +  uint64 destination_gas_price = 4;
Wait for router intregation contract support autogas

2025-02-21 07:49 UTC, colmazia commented on x/tunnel/keeper/keeper_packet_router_test.go
> +		CreatedAt: time.Now().Unix(),
can time be fixed?

2025-02-21 07:49 UTC, colmazia commented on x/tunnel/types/encoding_packet_abi.go
> +	if maxLen > 32 {
should we return error in case of string is over 32 bytes?

2025-03-12 09:37 UTC, colmazia submitted a review, later dismissed

2025-03-18 08:52 UTC, taobun commented on proto/band/tunnel/v1beta1/params.proto
> +  string router_integration_contract = 9 [(gogoproto.customname) = "RouterIntegrationContract"];
Why need custom name?

2025-03-18 10:46 UTC, taobun commented on x/tunnel/keeper/msg_server.go
> +	var isIBCRoute bool
Why need to move?

2025-03-18 11:05 UTC, RogerKSI commented on x/tunnel/types/encoding_packet_abi.go
> +
reuse function converting from prices to relay price from tss

2025-03-18 11:08 UTC, RogerKSI commented on x/tunnel/types/encoding_packet_abi.go
> +}
re-use same function from util

2025-03-26 09:45 UTC, taobun reviewed
Please resolve conflict

2025-04-03 08:23 UTC, RogerKSI requested changes

2025-04-03 08:23 UTC, RogerKSI commented on x/tunnel/client/cli/tx.go
> +		Use:   "router [destination-chain-id] [destination-contract-address] [destination-gas-limit] [initial-deposit] [interval] [signalDeviations-json-file]",
please help align name `signal-deviations` vs `signalDeviations`

2025-04-03 10:09 UTC, RogerKSI approved these changes

2025-04-11 03:41 UTC, taobun approved these changes

2025-04-11 04:09 UTC, merged