[chain] bind specific port for tunnel and add msg update route
bandprotocol/chain pull request #511
Opened 2024-12-03 11:20 UTC by taobun

Fixed: #XXXX

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2024-12-03 17:08 UTC, RogerKSI requested changes

2024-12-04 09:50 UTC, RogerKSI approved these changes

2024-12-04 10:52 UTC, satawatnack commented on proto/band/tunnel/v1beta1/tx.proto
> +  // tunnel_id is the ID of the tunnel to edit.
to update

2024-12-04 10:52 UTC, satawatnack commented on x/tunnel/keeper/ibc_test.go
> +		},
in this test `tunnel.eiei` should we also verify the number as well

2024-12-04 10:52 UTC, satawatnack commented on x/tunnel/keeper/ibc.go
> +}
add comment

2024-12-04 11:53 UTC, RogerKSI commented on x/tunnel/keeper/ibc.go
> +}
added comment.

2024-12-04 12:07 UTC, satawatnack approved these changes

2024-12-04 12:12 UTC, merged