[Tunnel] Add withdraw fee payer funds
bandprotocol/chain pull request #522
Opened 2024-12-12 09:47 UTC by satawatnack

## Implementation details
- add msg withdraw fee payer funds

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2024-12-12 10:21 UTC, RogerKSI approved these changes

2024-12-16 09:22 UTC, taobun requested changes

2024-12-16 09:22 UTC, taobun commented on proto/band/tunnel/v1beta1/tx.proto
> +  option (cosmos.msg.v1.signer) = "fee_payer";
creator?

2024-12-16 09:22 UTC, taobun commented on x/tunnel/keeper/msg_server.go
> +		sdk.AccAddress(tunnel.Creator),
should be AccAddressFromBech32?

2024-12-16 09:51 UTC, RogerKSI commented on proto/band/tunnel/v1beta1/tx.proto
> +  option (cosmos.msg.v1.signer) = "fee_payer";
fixed

2024-12-16 09:51 UTC, RogerKSI commented on x/tunnel/keeper/msg_server.go
> +		sdk.AccAddress(tunnel.Creator),
fixed

2024-12-16 09:56 UTC, RogerKSI approved these changes

2024-12-16 10:10 UTC, RogerKSI approved these changes

2024-12-17 08:14 UTC, taobun approved these changes

2024-12-17 09:31 UTC, merged