Command for migrate guanyu to laozi (cosmos part)
bandprotocol/chain pull request #53
Opened 2021-04-12 09:13 UTC by Benzbeeb

Fixed: #XXXX

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-04-16 06:36 UTC, ntchjb requested changes

2021-04-16 06:36 UTC, ntchjb commented on cmd/bandd/cmd/migrate.go
> +			}
Should `genDoc.ValidateAndComplete` be included?

2021-04-19 12:22 UTC, ntchjb approved these changes

2021-04-22 08:53 UTC, taobun approved these changes

2021-04-22 08:54 UTC, taobun requested changes

2021-04-22 08:54 UTC, taobun commented on cmd/bandd/cmd/migrate.go
> +			ibcTransferGenesis.Params.SendEnabled = false
Enable?

2021-04-22 08:54 UTC, taobun approved these changes

2021-04-22 08:56 UTC, merged