[tunnel] Check Route readiness
bandprotocol/chain pull request #535
Opened 2024-12-20 09:20 UTC by nkitlabs

Fixed:
- check if route is ready before producing a packet (if not deactivate that tunnel)
- can activate tunnel if the router is ready.

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2024-12-20 09:34 UTC, taobun approved these changes

2024-12-23 10:22 UTC, RogerKSI requested changes

2024-12-23 10:22 UTC, RogerKSI commented on x/tunnel/keeper/keeper_tunnel.go
> +		return found
do we need to check if it's open channel as well? or it's already done that?

2024-12-23 10:22 UTC, RogerKSI commented on x/tunnel/keeper/keeper_tunnel.go
> +		return found
if yes, need to update on MsgUpdateRoute as well?

2024-12-23 10:22 UTC, RogerKSI commented on x/tunnel/keeper/keeper_tunnel.go
> +
move this to above of setactive tunnel ID,, prevent state changes.

2025-01-02 07:14 UTC, nkitlabs commented on x/tunnel/keeper/keeper_tunnel.go
> +		return found
per discussed, TBD

2025-01-02 07:15 UTC, nkitlabs commented on x/tunnel/keeper/keeper_tunnel.go
> +
fixed

2025-01-02 10:45 UTC, satawatnack commented on x/tunnel/keeper/keeper_tunnel_test.go
> +func (s *KeeperTestSuite) TestActivateTunnelInactiveRoute() {
Should use TestActivateTunnel() and add this test case mai

2025-01-07 10:35 UTC, closed without merging