Implement multi send
bandprotocol/chain pull request #59
Opened 2021-04-21 15:37 UTC by Benzbeeb

Fixed: #XXXX

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-04-22 03:37 UTC, ntchjb requested changes

2021-04-22 03:37 UTC, ntchjb commented on cmd/bandd/cmd/multi_send.go
> +		Short: "Create and sign a multi-send tx",
```suggestion
		Short: "Send token to multiple accounts",
		Long: "Send equal amount of token to multiple accounts"
```

2021-04-22 03:37 UTC, ntchjb commented on cmd/bandd/cmd/multi_send.go
> +		Use:   "multi-send [amount] [to_address1] [to_address2] ....",
```suggestion
		Use:   "multi-send [amount_per_account] [to_address1] [to_address2] ....",
```

2021-04-26 04:24 UTC, songwongtp commented on cmd/bandd/cmd/multi_send.go
> +		Long: "Send equal amount of token to multiple accounts"
```suggestion
		Long: "Send equal amount of token to multiple accounts",
```

2021-05-05 04:02 UTC, taobun approved these changes

2021-05-07 06:25 UTC, ntchjb approved these changes

2021-05-10 09:14 UTC, merged