x/oracle/module.go
bandprotocol/chain pull request #62
Opened 2021-04-29 07:15 UTC by songwongtp

Fixed: #XXXX

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-04-29 08:06 UTC, ntchjb approved these changes
Approved. However, please note that in IBC module in Cosmos SDK v0.43, OnRecvPacket will only return acknowledgement, so we might need to find another way to solve this problem.

2021-04-29 08:10 UTC, songwongtp commented
Cosmos has to deal with this problem too. We can first wait and see how they will fix it.

2021-04-29 11:26 UTC, taobun requested changes

2021-04-29 11:26 UTC, taobun commented on x/oracle/module.go
> +		return nil, nil, sdkerrors.Wrapf(sdkerrors.ErrUnknownRequest, "cannot unmarshal ICS-20 oracle request packet data: %s", err.Error())
"cannot unmarshal oracle request packet data: %s"

2021-04-29 18:56 UTC, songwongtp commented on x/oracle/module.go
> +		return nil, nil, sdkerrors.Wrapf(sdkerrors.ErrUnknownRequest, "cannot unmarshal ICS-20 oracle request packet data: %s", err.Error())
67ea66d

2021-04-30 04:18 UTC, taobun approved these changes

2021-04-30 04:18 UTC, merged