Emitter: handle packet send fungible token
bandprotocol/chain pull request #78
Opened 2021-05-18 12:12 UTC by Benzbeeb

Fixed: #XXXX

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-05-19 03:47 UTC, taobun requested changes

2021-05-19 03:47 UTC, taobun commented on hooks/emitter/channel.go
> +	err := oracletypes.ModuleCdc.UnmarshalJSON(msg.Packet.Data, &data)
ibcxfertypes.ModuleCdc

2021-05-19 03:47 UTC, taobun commented on hooks/emitter/transfer.go
> +		err := h.cdc.UnmarshalJSON([]byte(events[0]), &data)
ibcxfertypes.ModuleCdc?

2021-05-19 03:47 UTC, taobun commented on hooks/emitter/channel.go
> +func (h *Hook) handleFungibleTokenPacket(
change name to `extractFungibleTokenPacket(ctx, packetData []byte,evMap common.EvMap, packet)`

2021-05-19 03:47 UTC, taobun commented on hooks/emitter/transfer.go
> +			}
This code look duplicate many times can refractor to one function?

2021-05-19 03:53 UTC, songwongtp commented on hooks/emitter/channel.go
>  	err := h.cdc.UnmarshalJSON([]byte(evMap[types.EventTypeSendPacket+"."+types.AttributeKeyData][0]), &data)
oracletypes.ModuleCdc

2021-05-19 07:51 UTC, taobun requested changes

2021-05-19 07:51 UTC, taobun commented on hooks/emitter/channel.go
> +	ctx sdk.Context, txHash []byte, msg *types.MsgRecvPacket, packet common.JsDict, evMap common.EvMap, extra common.JsDict,
Change msg -> data of packet ([]byte)

2021-05-19 07:51 UTC, taobun commented on hooks/emitter/transfer.go
> +		var data ibcxfertypes.FungibleTokenPacketData
using `extractOracleRequestPacket`

2021-05-21 03:45 UTC, taobun requested changes

2021-05-21 03:45 UTC, taobun commented on hooks/emitter/channel.go
> +func (h *Hook) getPacket(ctx sdk.Context, srcPort string, srcChannel string, sequence uint64, dstPort string, dstChannel string, isIncoming bool) common.JsDict {
newPacket

2021-05-21 03:45 UTC, taobun commented on hooks/emitter/channel.go
> +		h.Write("NEW_PACKET", packet)
I think extract only add field to packet and call write on caller.

2021-05-21 03:45 UTC, taobun commented on hooks/emitter/channel.go
> +	ctx sdk.Context, dataOfPacket []byte, packet common.JsDict, evMap common.EvMap,
reorder to ctx, data, evMap, packet

2021-05-21 03:45 UTC, taobun commented on hooks/emitter/channel.go
> +	ctx sdk.Context, txHash []byte, signer string, dataOfPacket []byte, packet common.JsDict, evMap common.EvMap, extra common.JsDict,
ditto

2021-05-21 03:45 UTC, taobun commented on hooks/emitter/channel.go
> +	ctx sdk.Context, txHash []byte, signer string, dataOfPacket []byte, packet common.JsDict, evMap common.EvMap, extra common.JsDict,
Remove txHash?

2021-05-24 05:51 UTC, taobun commented on hooks/emitter/channel.go
> +	h.Write("NEW_PACKET", packet)
This is your intention to put packet to list first then modify later?

2021-05-27 09:47 UTC, taobun approved these changes

2021-05-27 09:49 UTC, songwongtp approved these changes

2021-05-27 09:49 UTC, merged