Change result encode by codec instead of OBI
bandprotocol/chain pull request #84
Opened 2021-05-25 11:26 UTC by taobun

Fixed: #XXXX

## Implementation details
Noted! This pr break the consensus of current testnet!! We will use `laozi-testnet` branch for release update on testnet. Please don't use the master running the node.

2021-05-25 12:54 UTC, ntchjb requested changes

2021-05-25 12:54 UTC, ntchjb commented on x/oracle/keeper/owasm_test.go
> +		testapp.ParseTime(1581589890).Unix(), types.RESOLVE_STATUS_FAILURE, []byte(nil),
I think `[]byte(nil)` can be changed to `nil`.

2021-05-25 13:08 UTC, ntchjb approved these changes
LGTM 😄

2021-05-27 08:41 UTC, songwongtp approved these changes

2021-05-27 09:41 UTC, merged