Patch ibc testing for test msg ibc request
bandprotocol/chain pull request #88
Opened 2021-05-28 04:49 UTC by Benzbeeb

Fixed: #XXXX

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-06-02 04:08 UTC, taobun requested changes

2021-06-02 04:08 UTC, taobun commented on app/app.go
> +
Move to testapp

2021-06-02 07:23 UTC, taobun requested changes

2021-06-02 07:23 UTC, taobun commented on x/oracle/ibc_test.go
> +func TestTransferTestSuite(t *testing.T) {
Transfer?

2021-06-04 04:01 UTC, taobun approved these changes
LGTM thanks!

2021-06-04 04:28 UTC, songwongtp commented
merge https://github.com/bandprotocol/chain/pull/89 into this first

2021-06-04 04:36 UTC, songwongtp approved these changes

2021-06-04 04:37 UTC, merged